repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config
        args: [--application-directories, "./app:./"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [
          "git+https://github.com/PyCQA/pyflakes#egg=pyflakes",
          "git+https://gitlab.com/PyCQA/pycodestyle#egg=pycodestyle",
        ]
default_language_version:
  python: python3.8